start colors

diff --git a/touchx b/touchx
--- a/touchx
+++ b/touchx
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+###A touch and make executable
+
 die() { echo "$@"; exit 1; }
 
 if [[ $1 == -f ]]; then
@@ -16,7 +18,7 @@ touch "$@" && chmod +x "$@"
 
 
 if [[ -n $EXISTS ]]; then
-  [[ -z $FORCE ]] && die "$@ already exists, no change."
+  [[ -z $FORCE ]] && die "$@ already exists, no change (but was touched and +x-ed). Use -f to force."
 fi
 
 #echo "#!/bin/bash -e" >> "$@"
@@ -27,20 +29,27 @@ fi
 #echo 'die() { errcho "$@"; exit 1; }' >> "$@"
 #echo "" >> "$@"
 
+# NOTE: If interested in cygwin, et. al. put this after the determination of script_dir:
+#case `uname` in
+#  *CYGWIN*|*MINGW*|*MSYS*) script_dir=`cygpath -w ${script_dir}`
+#esac
+
+
 cat << 'EOF' >> "$@"
 #!/bin/bash -e
 
-script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
-case `uname` in
-  *CYGWIN*|*MINGW*|*MSYS*) script_dir=`cygpath -w ${script_dir}`
-esac
+ # For '###A' and the like, follow instructions and remove the leading space.
+ ###A one-line description
 
+ ###B longer description
+ ###B
+ ###B --including
+ ###B --flags           And descriptions for a usage statement
+
+script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"
 errcho() { echo "$@" 1>&2; }
 die() { errcho "$@"; exit 1; }
-
-ensurecmd() {
-  command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."
-}
+ensurecmd() { command -v $1 > /dev/null 2>&1 || die "$1 is required, but is not in PATH."; }
 
 
 EOF
